name: Check skip ci

on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      skip-ci: ${{ steps.check.outputs.skip-ci }}
    steps:
      - id: check
        run: echo "skip-ci=${{ endsWith(github.ref, '/skip-ci') || contains(github.event.head_commit.message, '[skip-ci]') }}" >> $GITHUB_OUTPUT
