name: Reusable flow

on:
  workflow_call:
    inputs:
      a-name:
        type: string

joss:
  reusable_workflow_job:
    steps:
      - name: echo passed name
        run: echo "passed is {a-name}"
